UKHomeOffice/lev-web

models/stubs.js, views/pages/details.html
"Add 'Date of registration' as a new separate field on the birth record
view at the bottom of the list of fields (below the Registration
district block, but as a separate field rather than part of that block)"
=> [LEVWEB-50] Add date of registration

assets/scss/app.scss
This removes the mock-hyperlink hover behaviour from the crown image's
parent div. This is desirable as we no longer have a link on this image.
"Design Review: Crown in Header is a link to nowhere
The Crown image in the header has a hover state so it looks like a link
but goes nowhere. Suggest removing this so it is just an image."
=> [LEVWEB-71] Remove hover decoration on crown image

api/mock/index.js, api/mock/package.json
It appears that process.name has slightly obtuse limits.
https://nodejs.org/dist/latest-v4.x/docs/api/process.html#process_process_title
This change ensures the teardown works on *nix and OSX.
=> fix for messy acceptance tests teardown

api/index.js
Adds support for displaying blocked records, which do not have all of
the fields available as normal records and so, would otherwise cause the
request to fail.
=> [LEVWEB-90] Support blocked records

api/index.js, assets/scss/app.scss, views/pages/details.html, views/pages/results.html
Adds a generic message to display on the results and details pages on
all flags returned by the API.
Includes CSS for displaying them. (Is there some GovUK pattern we can take off the peg instead?)
=>  [LEVWEB-152] Show generic message for all flags

app.js, assets/scss/app.scss, controllers/index.js, controllers/logged-out.js, routes/index.js, views/layout.html, views/pages/logged-out.html
Adds a "Logout" button to all pages. The button links through to the
KeyCloak logout URL, which then redirects back to a new endpoint,
/logged-out.
Unfortunately this does not, on its own, revoke access to the website.
This is probably a bug in go-keycloak-proxy but we are not certain at
this time. In order to secure the logout the endpoint clears the
kc-access cookie. Once the bug is fixed in go-keycloak-proxy this extra
functionality should be removed.
Note: This is not fully tested, as I could not think of a way to do so
without first deploying.
=> [LEVWEB-162] Log-out support

api/index.js, config.js, test/unit/api/index.js
Adds support for connecting to the API over HTTPS. (Still defaults to
HTTP.)
The protocol can now be configured via an environment variable.
=> [LEVWEB-236] HTTPS support when connecting to API

app.js, config.js, controllers/logged-out.js, views/layout.html
Makes use of the dedicated logout endpoint provided by newer versions of
keycloak-proxy. Eliminates the need for us to delete its cookie
ourselves.
=> [LEVWEB-258] Use proper logout endpoint

test/acceptance/expectedRecords.js, test/acceptance/spec/10-search.js
Makes the searches in the e2e tests only search on one forename when
looking for multiple results.
=> [LEVWEB-292] Only search on first forename

test/acceptance/spec/10-search.js, views/pages/results.html
Re-order the information on the results pages so that mother appears
above father the same way it does on the details page.
=> [LEVWEB-307] Re-order info on result page

assets/scss/app.scss, views/pages/details.html, views/pages/results.html, views/pages/search.html
Removes the right-hand margin on the last button in order to stop the
buttons from wrapping on IE11 in a narrow window.
=> [LEVWEB-310] Remove margin on the last button

lib/lev-request.js
Allows setting the key and cert but not the CA for example.
=> Do not require all TLS env vars to be set together

.gitignore, controllers/search.js, test/acceptance/spec/10-search.js
Dates of birth can now be entered into the search box in a short format. The short format is exactly **eight** numbers of the form **DDMMYYYY**.
=> LEVWEB-334: Allow short date of birth

assets/js/details.polyfill.js, views/layout.html
Adds temporary styles to hide all details contents (except the summary) during the page load, which are removed by default styling if javascript is not enabled, or removed by javascript otherwise.
=> Stop system number hint flicker during page load

test/acceptance/spec/10-search.js, views/pages/search.html
Show the system number hint (by expanding the details section), if a system number validation error occurs.
=> Show system number hint after validation error

fields/index.js, locales/en/default.json, test/acceptance/spec/10-search.js, test/unit/controllers/search.js
A new validation rule has been added to check that system numbers are **9 digit numbers** as expected.
=> Validate system numbers have exactly 9 digits

locales/en/default.json
Changed the example text for the date of birth field to a valid (and much more auspicious date)
=> Update date of birth example

controllers/search.js, test/unit/controllers/search.js
Only allow dates with the full 4 digit year, or the shorthand 2 digit format.
Valid date formats:
- D/M/YY
- D/M/YYYY
- DDMMYY
- DDMMYYYY
=> Disallow 1 and 3 digit years for date of birth

api/index.js, test/acceptance/spec/20-details.js, test/unit/api/index.js, views/pages/details.html
The "Birth jointly registered" (values: "Yes"/"No") property of the details page has been changed to "Birth registered by" (values now come from the API/DB).
=> Change "jointly registered" to "registered by"

views/pages/search.html
Changed the `title` attribute of the system number hint image to describe the system number and define its location on a birth certificate.
=> Improve system number hint accessibility

lib/logger.js
I don't think this is the solution in the long run. I think we should either use hmpo-logger or write our own.
=> Quick fix for logging out errors in JSON

package.json
Pins http-proxy to the last working version in order to avoid a bug that
breaks our acceptance tests.
=> Pin to last working version of http-proxy

app.js, lib/health.js, package.json, test/acceptance/spec/02-health.js, test/unit/lib/health.js
Add the `healthz` and `readiness` endpoints used by Kubernetes management probes.
=> Add kubernetes management endpoints

package.json
Improve the development workflow so that `npm run dev` now automatically does:
- the SASS compilation when the styles are updated
- the linting and uglification of the frontend JS when the client code changes
- linting and unit testing when the app code or unit test code changes
- end-to-end tests run when the test code changes
Plus, manual tests can be run in the browser.
NOTE: Manual and end-to-end tests will be hitting the mock API.
=> LEVWEB-677 Automate common dev tasks

api/helpers.js, api/index.js, controllers/audit.js, fields/audit.js, lib/custom-validators.js, locales/en/default.json, test/acceptance/mixins/audit.js, test/acceptance/spec/23-user-activity.js, test/unit/api/helpers.js, test/unit/api/index.js, test/unit/controllers/audit.js, test/unit/lib/custom-validators.js, views/pages/user-activity.html, views/partials/audit-report.html
Add a search filter to allow the User Activity report to be limited to a specific user (by entering an exact username) or group of users (by entering a common term to match usernames).
=> LEVWEB-638 Add audit user filter

package.json, test/smoke/.eslintrc.yaml, test/smoke/config.js, test/smoke/smoke-tests.js
Tries to find the non-existent record with system number `404`.
Requires user details of a system user with the `monitoring` role assigned.
=> [LEVWEB-730] Basic smoke test

Dockerfile-e2e, package.json
The environment variable `SMOKE_TEST` can now be used to change the tests run by the `lev-web-e2e` image to choose between the E2E tests (default) and the smoke tests (example below).
```
docker run -e SMOKE_TEST=true lev-web-e2e
```
=> Switch based browser tests

package.json
Pins the webdriverio module to v4.8 to workaround what appears to be a
bug in the most recent v4 in the `getText` method when used to get data
from tables.
=> [LEVWEB-841] Pin webdriverio to v4.8

config.js, lib/lev-request.js, test/unit/lib/lev-request.js
Adds an environment variable, LEV_TLS_VERIFY, that when set to 'false'
will disable verification of the API's server certificate.
Somewhat related to #293.
=> [LEVWEB-839] Env var to disable API verification

.drone.yml
In the docs they no longer pin the version so we probably shouldn't
either.
=> [LEVWEB-585] Don't pin slack-plugin version

api/index.js, config.js, package.json, test/acceptance/config.js, test/acceptance/spec/23-user-activity.js, test/unit/api/index.js
Constrain the maximum audit report date range for the table to `92 days` (roughly a Quarter).
This should stop the accidental crippling of LEV by requests for MASSIVE amounts of audit data!
=> [LEVWEB-871] Limit audit date range

app.js, test/acceptance/spec/06-headers.js
Adds some headers for security hardening. Should discourage caching and
the use of frames.
These headers are not applied to static assets.
=> [LEVWEB-475][LEVWEB-476] Harden headers

api/helpers.js, views/pages/death-details.html, views/pages/marriage-details.html
Fixes some bugs in which the new deaths and marriages pages pages were
missing some fields.
=> Fix: Missing fields in deaths and marriages

views/pages/death-results.html, views/pages/marriage-results.html
Builds the links from the id parameter rather than a system-number
parameter.
=> [LEVWEB-894] Fix broken links on results page

Dockerfile
This is to work around an issue in an upcoming version of Kubernetes.
=> [LEVWEB-921] Declare user by UID rather than name

assets/scss/details.scss
Currently buttons placed inside flags are out of alignment due to their
display mode of `inline-block` as well their margins.
=> [LEVWEB-954] Fix: Buttons in flags alignment

views/layout.html
Removed the explicit redirect on the 'Sign out' link to take advantage
of keycloak-proxy's default of providing the hostname through to
Keycloak.
=> [LEVWEB-1033] Update Sign-out link

.drone.yml
Adds the test annotation to both of the Dev environments so that there
will not be any missing information when we report on changes.
=> Annotate both Dev environments

.drone.yml, api/helpers.js, api/index.js, docker-compose-local-api.yml, docker-compose.yml, fields/death.js, fields/marriage.js, locales/en/default.json, package.json, views/pages/death-results.html, views/pages/death-search.html, views/pages/marriage-results.html, views/pages/marriage-search.html
Updates the search fields for the death and marriage prototypes according to the user needs. Specifically marriage searches are now done using the date of marriage and death searches can provide the date of death instead of the date of birth.
Also:
- node-sass is upgraded to aid development on Node.js v8
- The version is bumped to reflect the interface change and the new API version required
=> Update death and marriage search fields

test/acceptance/spec/23-user-activity.js
It isn't safe to assume that the test user will always appear in the
first of the audit data.
=> [LEVWEB-1078] Fix brittle acceptance test

test/acceptance/spec/06-link-checker.js
Errors are reported more clearly, with a URL and selector to help pinpoint the source.
=> [LEVWEB-625] Broken link/missing asset report ++

test/acceptance/spec/06-link-checker.js
Before error pages (or pages that unintentionally resulted in errors!) were not being checked.
There are also some minor improvements for code clarity.
P.S.
I suggest you look at the individual commits themselves as they are far easier to follow than github's busted wonky diff!
=> [LEVWEB-625] Improve broken link and missing asset report

views/pages/marriage-details.html
Switches to using gender neutral terms on the marriage details page.
In the future we could look at changing the terms we use depending on
whether it is a gay marriage or not.
=> [LEVWEB-1167] Gender neutral terms on marriages

.drone.yml, Makefile, docker-compose-test.yml
No longer tries to take ports on the host when testing in Docker and
also attempts to tear down any previous builds before testing.
=> Make CI more reliable

.dockerignore, Dockerfile, Dockerfile-testing, Makefile
The performance tests currently fail in CI due to the docker-compose networks following a new format.
This PR also includes some attempts to speed up builds.
=> Fix failing performance tests in CI

test/acceptance/spec/21-death-details.js, test/acceptance/spec/22-marriage-details.js, test/unit/ui/index.js, views/pages/marriage-details.html
Renames the marriage registration date to 'date (filed)'.
Also hides it from view for normal users. (We might want to review this
later.)
=> [LEVWEB-1227] Rename and hide marriage reg date

api/helpers.js, test/unit/api/index.js
Displays the red, "Refer to GRO" flag when a marginal note exists on a
marriage record.
=> [LEVWEB-1272] Display red flag for marginal notes
