assets/scss/app.scss, assets/scss/icons.scss, assets/scss/validation.scss, config.js, package.json, views/pages/query.html, views/partials/form.html, views/partials/maincontent-left.html, views/partials/navigation.html, views/partials/page-header.html, views/partials/validation-sumary.html
- fill in query page with form content
- add header and title
- add scss styles
- add script for sass
=> Add content to query page

assets/scss/app.scss, controllers/details.js, controllers/index.js, controllers/list.js, controllers/query.js, models/index.js, package.json, routes.js, test/common.js, test/unit/controllers/details.js, test/unit/controllers/list.js, test/unit/controllers/query.js, views/pages/details.html
- add details page
- add controllers for all pages
- add promisfied stub model
- a bunch of unit tests
=> Details page

app.js, config.js
- config session secret
- inject into app middleware
=> Tidy up session secret

controllers/details.js, controllers/results.js, controllers/search.js, lib/helpers.js, routes.js, test/unit/controllers/details.js, test/unit/controllers/results.js, views/pages/search.html, views/partials/buttons.html
- add lib/helpers#serialise
- add querystring onto locals
- add values to search form
=> Make edit buttons redirect to search page with values

views/pages/search.html
"Change 'System number' text on search screen
Change 'System number' to 'System number from birth certificate' - just
on the search screen"
=> [LEVWEB-48] Change "System Number" label

views/pages/search.html
"Take out Nationality field in Search criteria"
=> [LEVWEB-51] Remove "Nationality" field

models/stubs.js, views/pages/details.html
"Add 'Place of birth' to both parents on the birth record view - it
should be below any name fields and above the 'Occupation' field"
=> [LEVWEB-49] Add parent place of birth

controllers/search.js, test/unit/controllers/search.js, test/unit/temp-test.js, views/pages/results.html
- show no results message when query returns no results
- remove the test test
=> No results message

package.json, views/layout.html
- replace pointer to partial with html from partial
- update to 2.0.0 frontend toolkit
=> Override gov uk template

views/layout.html
=> Remove link to gov.uk

assets/scss/app.scss, views/pages/details.html
- amend spacing between details table cells
- amend font-size
- amend first column width
=> Design review changes @lev-web-55

test/acceptance/query.js, views/pages/search.html
s/Applicants Details/Applicant's details/
=> [LEVWEB-58] Correct heading on search page

app.js, middleware/error.js, views/pages/error.html
=> Handle errors with middleware

assets/scss/app.scss
Ensure we always align to the top of table cells
=> Remove responsive font sizes

controllers/index.js, controllers/login.js, routes.js, test/acceptance/details.js, test/acceptance/login.js, test/acceptance/results.js, test/acceptance/search.js, views/pages/login.html
- basic sign in
- routes and controller
=> LEVWB-64: Sign in Screen

test/acceptance/details.js, test/acceptance/results.js, views/partials/buttons.html
- update href values in edit and new search button/link
- add acceptance tests for clicking the link
=> LEVWEB-77: Update links to point at correct url

app.js, kube/dev/controller.yaml
* Ships static resources as we do not yet have nginx in place
* Provides location of the API through environment variables when running in kubernetes
=> [LEVWEB-47] Hook up LEV Interface to API (update 1)

api/index.js, controllers/search.js, middleware/error.js, test/unit/controllers/search.js
Correctly handles errors from the API. Fixes some problems with the
error handler.
Also fixes some linting errors.
=> [LEVWEB-157] Don't hang on bad API responses

api/index.js, controllers/details.js, controllers/results.js, test/unit/api/index.js, test/unit/controllers/details.js, test/unit/controllers/results.js
Provides new methods on the 'api' modules for hitting specific endpoints
(read() now makes use of these). Also fixes some linting errors.
=> Yo dawg!: Further re-factor to avoid needless arrays

app.js, lib/logger.js, middleware/error.js, package.json
Adds logging to the app. The code is lifted from brp_app for the most
part.
=> [LEVWEB-241] Add simple logging

Dockerfile, README.md, package.json, test/acceptance/common.js, test/acceptance/config.js, test/acceptance/details.js, test/acceptance/expectedRecord.js, test/acceptance/expectedRecords.js, test/acceptance/logout.js, test/acceptance/mock-proxy/index.js, test/acceptance/results.js, test/acceptance/search.js
- Login step added before all tests when on dev or preprod
- Logout test added
- Tests use htmlunit instead of phantomjs due to issues with phantomjs and the keycloak login scree
- Dockerfile updated so tests can use selenium htmlunit instead of phantomjs
- Config added to enable running tests in different environments
- Many minor changes so tests work with htmlunit and chrome as they handle spaces between table elements differently
- Chimp version updated
=> Updates so chimp tests work on dev and preprod environments

.dockerignore, E2E_test_Dockerfile, README.md, test/acceptance/common.js
And some bug fixes on the tests
=> E2E tests run in docker container

lib/hof-standalone.js, test/acceptance/search.js
* Adds some more acceptance tests.
* Adds fix for nginx proxy.
=> [LEVWEB-127] Form validation

assets/scss/app.scss, views/pages/details.html, views/partials/buttons.html
* [LEVWEB-276] Make "Edit search" into a button
* [LEVWEB-277] Add white-space below buttons
=> [LEVWEB-276] [LEVWEB-277] Update button styling

controllers/search.js, fields/index.js, lib/hof-standalone.js, locales/en/default.json, test/acceptance/spec/10-search.js
Ensures that the DOB is entered in British format and that it is a valid
date.
=> [LEVWEB-62] Date of birth validation

app.js, assets/scss/app.scss, views/layout.html, views/pages/details.html, views/pages/error.html, views/pages/login.html, views/pages/results.html, views/pages/search.html, views/partials/navigation.html
Also:
* redesigns the black header area to give us centre alignment.
* addresses LEVWEB-291.
=> [LEVWEB-249] Reposition logout link

fields/index.js, locales/en/default.json, test/acceptance/spec/10-search.js, test/acceptance/spec/20-details.js, test/unit/controllers/search.js
* Makes forename(s) and DOB mandatory fields unless a system number is
provided.
* Makes system number optional no matter what. i.e. It assumes the user
is searching by name, which leads to saner validation messages when
submitting an empty form.
=> [LEVWEB-289] Make most fields mandatory

fields/index.js, locales/en/default.json, test/acceptance/spec/10-search.js, test/acceptance/spec/20-details.js, test/unit/controllers/search.js
Note: I was unable to test this manually so am resorting to pushing it to master so that it can be tested in CI.
Please do not merge until #121 has been merged.
=> [LEVWEB-292] Fix end to end tests

locales/en/default.json, test/acceptance/mixins/search.js
All done with HOF. - See it was a good idea after all!
=> [LEVWEB-302] Add format hint on DOB field

assets/scss/app.scss, controllers/details.js, controllers/search.js, test/acceptance/spec/10-search.js, test/acceptance/spec/20-details.js, views/pages/details.html, views/pages/results.html
New links added on details page for:
- back to results
- edit search
=> Links on details page

assets/scss/app.scss
"...from ocean grey to military grey.
Or is it the other way around?.."
=> [LEVWEB-309] Change button colour

locales/en/default.json, test/acceptance/spec/10-search.js
Changes the word "integer" to "number" in the validation error message
for system number.
...because, you know, people be ignorant.
=> Changes "integer" to "number" in error message

test/acceptance/expectedRecord.js, test/acceptance/expectedRecords.js, test/acceptance/spec/10-search.js, test/acceptance/spec/20-details.js
Updates the acceptance tests to search on the person's current name
rather than their original name.
=> Update tests to search on the current name

Dockerfile
Forces the API specification to be refreshed whenever the app changes.
=> Force refresh of API spec

Dockerfile, api/index.js, assets/scss/app.scss, assets/scss/details.scss, locales/en/default.json, package.json, test/unit/api/index.js, views/pages/details.html, views/pages/results.html
* Updates flags to correctly handle the new API response and reflect new
directions. Makes the code more defensive in relation to blocked
records.
* Adds amber warning flags to SASS.
* Simplifies Dockerfile.
=> [LEVWEB-156] Update flags for new API response

api/index.js, test/acceptance/expectedRecord.js, test/acceptance/expectedRecords.js, test/acceptance/spec/20-details.js, test/unit/api/index.js, views/pages/details.html
Adds the mother's surname from a previous marriage to the details page.
=> [LEVWEB-343] Display previous marriage surname

test/acceptance/expectedRecords.js
Fixes a bug in the end-to-end tests.
=> [LEVWEB-343] Fix E2E tests

api/index.js, config.js, lib/lev-request.js, lib/request-helper.js, lib/request-with-oauth2.js, test/unit/lib/lev-request.js, test/unit/lib/request-with-oauth2.js
Adds support for client certificates. i.e. Mutual TLS. The certificates
can be configured by setting their file paths via environment variables.
=> [LEVWEB-356] Support client certificates

package.json
This means that postinstall will only pass when all of the stages pass
and not just the last.
=> Update postinstall script to fail early

lib/request-with-oauth2.js
Defends against errors in making HTTP requests besides those covered by
a status code.
=> Bugfix: Errors on making a request crash the app

assets/scss/app.scss, views/layout.html
=> Stop system number hint flicker during page load

fields/index.js
Performs system number-based searches rather than name-based searches
when both are provided by the user.
=> Bug-fix: Prefer system number searches

views/layout.html
=> Remove the cookie banner

app.js, controllers/details.js, middleware/not-found.js, routes/index.js, test/unit/controllers/details.js, views/pages/error.html
Provides a few quick patch ups. In the future we should refactor
properly but this should be a considerable improvement on what we have
at the moment.
* Prevents the search form from appearing on all routes
* Adds prettier 404 pages via dedicated middleware
* Updates the details controller to correctly use the 404 and error
pages
=> Misc bug-fixes

controllers/search.js, test/unit/controllers/search.js
Even when a 'not found' error is handled it could still be passed
further down the stack.
=> Bugfix: Handled errors should not be passed on

controllers/search.js
Splits up a function into smaller ones.
=> Minor clean-up

.travis.yml, Dockerfile
This is so we can use more recent versions of HOF.
=> [LEVWEB-477] Upgrade npm to v3

assets/scss/app.scss, assets/scss/details.scss, assets/scss/results.scss, test/acceptance/spec/20-details.js, views/pages/details.html
See individual commit messages for more details.
The **search** page now looks like this:
The **results** page:
The **details** page:
=> Style application as a whole

assets/scss/app.scss, assets/scss/details.scss, assets/scss/results.scss
Made some bits match the new frontend toolkit styles, which will hopefully be replaced by updating the toolkit at some point...
=> Update styles to please Tom

assets/scss/app.scss, assets/scss/details.scss, assets/scss/results.scss
Just a couple of minor tweaks.
=> Update styles to please Tom (part 2)

lib/request-with-oauth2.js, test/unit/api/index.js, test/unit/lib/request-with-oauth2.js
=> Reinstate the grant_type parameter

package.json, test/acceptance/config.js, test/acceptance/spec/02-health.js
=> Correct config for e2e tests

api/helpers.js, api/index.js, assets/scss/app.scss, assets/scss/user-activity.scss, controllers/audit.js, controllers/index.js, controllers/search.js, fields/audit.js, lib/custom-validators.js, lib/request-with-oauth2.js, locales/en/default.json, routes/index.js, test/unit/api/helpers.js, test/unit/api/index.js, test/unit/controllers/audit.js, test/unit/controllers/search.js, test/unit/lib/custom-validators.js, views/pages/user-activity.html, views/partials/audit-report.html
Adds the User Activity report at endpoint `/audit/user-activity`
The report shows an aggregate of user activity, specifically the number of times a user has searched the system in a day.
The report is constrained by a required date range.
=> LEVWEB-637 User Activity report UI

assets/scss/user-activity.scss, views/pages/user-activity.html
Correct the style issues that crept in after the first PR.
=> LEVWEB-640 Fix app styling

controllers/audit.js, test/unit/controllers/audit.js
Divide everything by `2` so Nigel doesn't have to.
=> LEVWEB-688 Half the user counts in the audit report

test/acceptance/mixins/login.js, test/acceptance/spec/23-user-activity.js
Ensure the acceptance tests also work as end-to-end tests.
=> [LEVWEB-701] Fix E2E tests

api/helpers.js
Adds the body of the response to errors generated by bad responses from
the API to ease debugging.
=> More helpful errors on API responses

test/acceptance/mixins/login.js
Makes the end-to-end tests compatible with the new, GovUK-styled
Keycloak theme.
=> [LEVWEB-717] Compatibility with new Keycloak theme

Dockerfile
=> Upgrade node.js version for security

lib/lev-request.js, test/unit/lib/lev-request.js
Reverts UKHomeOffice/lev-web#293
=> Revert "Fix cert issue"

README.md
=> ---------------> dummy change

README.md
Reverts UKHomeOffice/lev-web#295
=> Revert "---------------> dummy change"

test/acceptance/mixins/audit.js, test/acceptance/mixins/login.js, test/acceptance/mixins/search.js, test/acceptance/spec/05-login.js, test/smoke/smoke-tests.js
Stop the e2e test logs from being spammed by the deprecation warnings for the "submit form" action. Swutched to "clicking the submit button" instead.
=> [LEVWEB-840] Fix submit deprecation warnings

.snyk
Patches some vulnerabilities via Snyk.
=> Patch some vulnerabilities in dependencies

views/pages/details.html
Changes the court order in place flag to red from amber.
=> [LEVWEB-860] Make amber flag red

.drone.yml
This reverts commit 667788c7d72ff0259e6c18f62d75814504f685f6.
=> Revert "[LEVWEB-858] Eliminate docker login step"

.drone.yml
The trick I was attempting with swapping out secrets does not appear to
work. This commit works around the problem by using a simpler strategy.
=> [LEVWEB-585] Simplify Drone variables to avoid bug

middleware/error.js, test/acceptance/mixins/error.js, test/acceptance/spec/00-common.js, test/acceptance/spec/12-error.js, test/smoke/smoke-tests.js
Make the "Start Again" link on the Error page return the user to their previous activity (not just the Birth Search page).
=> [LEVWEB-873] Fix Start Again link

.drone.yml
Trigger the last successful drone build, to promote changes from Dev to UAT.
=> [LEVWEB-879] Promote successful Dev deploys to UAT

.drone.yml
DSP and ACP have diverged a little more so this is necessary.
=> Add more secrets dedicated to DSP

.drone.yml, Makefile, docker-compose-local-api.yml, docker-compose.yml, test/acceptance/mock-kc-proxy/front.js, test/acceptance/mock-kc-proxy/index.js, test/perf/artillery.config.yml, test/perf/compose_perf_tests.sh
This also includes a nice docker-compose for the application.
=> Add artillery tests for lev-web

views/pages/marriage-results.html
Was previously linking to the births details pages.
=> [LEVWEB-894] Fix marriage details link

views/pages/death-results.html, views/pages/marriage-results.html
... when no results are found.
=> Fix: Include system number in search summary

locales/en/default.json, views/pages/details.html
Add link to previous registration.
=> [LEVWEB-346] Add link to previous registration.

test/acceptance/mixins/login.js
We have simplified the authentication mechanism so this element no
longer exists.
=> No need to click summary element anymore

api/helpers.js, package.json, views/pages/death-details.html, views/pages/death-results.html, views/pages/death-search.html, views/pages/marriage-details.html, views/pages/marriage-results.html, views/pages/marriage-search.html
Also,
- removes references to births from the marriage and death prototypes
- adds support for blocked records
- adds support for linking to previous records
=> [LEVWEB-955] Show full marriage and death data

package.json
...pull from Quay instead of Artifactory.
=> Correct the docker repo for the pulling lev-api

.drone.yml
...by checking the `docker logs` for the e2e test job.
=> [LEVWEB-1078] Get more info about failed deploys

.drone.yml
Locally I had issues with appending vs writing (`>>` vs `>`), so this uses write instead...
=> [LEVWEB-1078] Change the way the log tailing works

.drone.yml, api/helpers.js, docker-compose-local-api.yml, docker-compose.yml, package.json, test/acceptance/expected-death-record.js, test/acceptance/expected-death-records.js, test/acceptance/expected-marriage-record.js, test/acceptance/expected-marriage-records.js, test/acceptance/mixins/details.js, test/acceptance/mixins/error.js, test/acceptance/mixins/results.js, test/acceptance/mixins/search.js, test/acceptance/spec/12-error.js, test/acceptance/spec/14-death-search.js, test/acceptance/spec/16-marriage-search.js, test/acceptance/spec/21-death-details.js, test/acceptance/spec/22-marriage-details.js, views/pages/death-details.html, views/pages/death-results.html
Also, fixes a bug in which international dates were not being re-formatted to British ones.
=> Add acceptance tests for marriages and deaths

test/acceptance/spec/06-link-checker.js
Expands the coverage of the link checker to include the death and
marriage forms.
=> [LEVWEB-1086] Expand coverage of link checker

api/helpers.js, test/acceptance/spec/22-marriage-details.js, views/pages/marriage-details.html, views/pages/marriage-results.html
Also adds links to the next registration in the chain and adds a
re-registration flag to the results page.
=> [LEVWEB-1097] Add missing marriage fields

.drone.yml
Removes the old environment from the CI/CD pipeline.
=> Only deploy to one place

.drone.yml, api/helpers.js, docker-compose-local-api.yml, docker-compose.yml, package.json, test/acceptance/expected-marriage-record.js, test/acceptance/expected-marriage-records.js, test/acceptance/mixins/search.js, test/acceptance/spec/22-marriage-details.js, views/pages/marriage-details.html, views/pages/marriage-results.html
Updates to lev-api v0.7 to take advantage of extra information available on marriages.
=> [LEVWEB-1120] Update to lev-api v0.7

test/acceptance/spec/16-marriage-search.js, test/acceptance/spec/22-marriage-details.js
`record.placeOfMarriage` is now an object so we must select the property we require.
=> [LEVWEB-1120] Fix: Correct acceptance tests

test/acceptance/spec/22-marriage-details.js
Add missing conditional skip code to other full marriage test.
=> [LEVWEB-1173] Skip full marriage tests in E2E mode

package.json, test/unit/controllers/details.js, test/unit/controllers/marriage-details.js, test/unit/lib/lev-request.js, test/unit/ui/index.js
Make sure all the tests handle promise rejections, to avoid `node` exiting abruptly.
...And update the `sinon` module dependency.
=> [LEVWEB-1184] No unhandled promise rejections

assets/js/index.js, test/acceptance/mixins/search.js
Make sure the default focused element on search pages is the `#system-number` field.
=> [LEVWEB-1187] Focus system number field

config.js
Allows larger date ranges to be queried.
=> [LEVWEB-1162] Increase audit range

assets/scss/app.scss, test/acceptance/mixins/search.js, test/acceptance/spec/10-search.js, views/pages/search.html
The hint lists the various types of supported date formats, and is shown when the date has been entered incorrectly.
=> [LEVWEB-433] Add detailed hint for date of birth field

controllers/death-details.js, controllers/marriage-details.js, lib/helpers.js, test/acceptance/spec/21-death-details.js, test/unit/controllers/marriage-details.js, test/unit/lib/helpers.js, views/pages/death-details.html
Access to full death record limited to users with the special role header (same as marriages).
=> [LEVWEB-1186] Limit death details

assets/js/index.js, test/acceptance/spec/10-search.js, test/acceptance/spec/14-death-search.js, test/acceptance/spec/16-marriage-search.js
...to make correcting errors easier.
=> [LEVWEB-1195] Focus fields that fail validation

hooks/pre-commit, package.json
Helps defend against test suppression from erroneously included `.only` modifiers left in test code.
=> [LEVWEB-1199] Add git "pre-commit" hook

test/acceptance/spec/14-death-search.js, views/pages/death-search.html
...and check that it is automatically displayed when the user enters a
value that fails the date validation checks.
=> [LEVWEB-1192] Add details hint to death date field

test/acceptance/spec/16-marriage-search.js, views/pages/marriage-search.html
...and check that it is automatically displayed when the user enters a
value that fails the date validation checks.
=> [LEVWEB-1193] Add details hint for marriage date

package.json, test/smoke/smoke-tests.js
Expands the smoke tests in order to:
- test the form itself
- test deaths end to end
- test marriage end to end
=> [LEVWEB-1180] Expand smoke tests

test/acceptance/spec/22-marriage-details.js, views/pages/marriage-details.html
This is never printed so it should be removed.
=> [LEVWEB-1227] Remove filed date entirely

views/pages/partnership-details.html
Take the unnecessary header out of the CP UI
=> [LEVWEB-1227] Correct a minor issue with CP UI

locales/en/default.json, test/acceptance/mixins/search.js, test/acceptance/spec/18-partnership-search.js, test/acceptance/spec/23-partnership-details.js, views/pages/partnership-details.html, views/pages/partnership-results.html, views/pages/partnership-search.html
Includes the word 'civil' in 'civil partnership'.
=> [LEVWEB-1233] Include the word 'civil'

test/acceptance/spec/20-details.js, views/pages/details.html
=> [LEVWEB-1234] Amend label for surname at marriage

api/helpers.js, test/acceptance/expected-death-record.js, test/acceptance/expected-death-records.js, test/acceptance/spec/21-death-details.js, views/pages/death-details.html, views/pages/marriage-details.html, views/pages/partnership-details.html
We now have more information on deaths available to us and should
display it on the deaths pages when the users has the permissions to do
so.
=> [LEVWEB-1106] Add new information to deaths 

.drone.yml, api/helpers.js, api/index.js, controllers/audit.js, controllers/death-details.js, controllers/death-search.js, controllers/details.js, controllers/marriage-details.js, controllers/marriage-search.js, controllers/partnership-details.js, controllers/partnership-search.js, controllers/search.js, docker-compose-local-api.yml, docker-compose-test.yml, docker-compose.yml, lib/lev-request.js, package.json, test/acceptance/spec/14-death-search.js, test/unit/api/index.js, test/unit/controllers/audit.js, test/unit/controllers/details.js, test/unit/controllers/marriage-details.js, test/unit/controllers/partnership-details.js, test/unit/controllers/search.js, test/unit/lib/lev-request.js, views/pages/death-results.html
We should test against the new version of the API in order to expose bugs.
Once the bugs are exposed we can fix them.
=> [LEVWEB-1396] Update to work with v0.15 lev-api

Dockerfile-e2e, package-lock.json
Summary of the  changes:
- Tactical fix to disable ssl validation at the test client side to resolve build issue
=> DVAD-2805: Build-Certificate-Issue

.drone.yml
Reverts UKHomeOffice/lev-web#456
=> Revert "updated docker run command to add network as host"
